### ISSUE TITLE
UnhandledPromiseRejectionWarning just after start of script

### ISSUE THREAD

**Issue by pimviergever** [koktaildotcom/com.p1.smartmeter-dsmr.reader#15]
Hi,

Running version 2 on rpi3. Just after a minute this error occurred. Can I do some additional troubleshooting?

(node:3230) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
at module.exports.telegram (/opt/smartmeter/node_modules/node-dsmr/lib/parser.js:99:21)
at Connection.self._connection.on.line (/opt/smartmeter/node_modules/node-dsmr/lib/index.js:78:16)
at Connection.emit (events.js:198:13)
at ReadLineParser.<anonymous> (/opt/smartmeter/node_modules/node-dsmr/lib/connection.js:62:12)
at ReadLineParser.emit (events.js:198:13)
at addChunk (_stream_readable.js:288:12)
at readableAddChunk (_stream_readable.js:265:13)
at ReadLineParser.Readable.push (_stream_readable.js:224:10)
at ReadLineParser.Transform.push (_stream_transform.js:151:32)
at ReadLineParser._transform (/opt/smartmeter/node_modules/@serialport/parser-delimiter/lib/index.js:35:12)
(node:3230) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3230) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by koktaildotcom** [comment]
This is related to an old version of node-dsmr
