### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by djvanas** [koktaildotcom/com.p1.smartmeter-dsmr.reader#5]
Hi I'm encountering an issue whereby the script stops every couple of days. The following error is shown on my Pi;

(node:12222) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at module.exports (/home/pi/com.p1.smartmeter-dsmr.reader/node_modules/node-dsmr/lib/parser.js:99:21)
    at Connection.<anonymous> (/home/pi/com.p1.smartmeter-dsmr.reader/node_modules/node-dsmr/lib/index.js:78:16)
    at Connection.emit (events.js:315:20)
    at ReadLineParser.<anonymous> (/home/pi/com.p1.smartmeter-dsmr.reader/node_modules/node-dsmr/lib/connection.js:62:12)
    at ReadLineParser.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at ReadLineParser.Readable.push (_stream_readable.js:214:10)
    at ReadLineParser.Transform.push (_stream_transform.js:152:32)
    at ReadLineParser._transform (/home/pi/com.p1.smartmeter-dsmr.reader/node_modules/@serialport/parser-delimiter/lib/index.js:35:12)
(node:12222) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12222) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by koktaildotcom** [comment]
This is an error from the package node-dsm.
