### ISSUE TITLE
Script error. Can you help me out ?

### ISSUE THREAD

**Issue by Itsmmai** [koktaildotcom/com.p1.smartmeter-dsmr.reader#8]
/home/ab/p1/src/p1.js:1
const dsmr = require('node-dsmr') const fetch = require('node-fetch') const logger = require('winston')
                                  ^^^^^

SyntaxError: Unexpected token const
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by koktaildotcom** [comment]
You can run it witih node src/p1.js
